### PR TITLE
Update player.tsx

### PR DESCRIPTION
**Pull request by dreadthief125**

### CODE REVIEW

**Comment by afkvido** [comment]
why remove membership hacks @hostedposted?

**Comment by AgrTheDev** [comment]
Legal

**Comment by afkvido** [comment]
really dog

**Comment by afkvido** [comment]
think of it like that and yeah, the whole hacking service is illegal

**Comment by afkvido** [comment]
Also where'd the extension go?

**Comment by AgrTheDev** [comment]
> think of it like that and yeah, the whole hacking service is illegal

Membership hacks were cutting into prodigy's revenue. Most of the other hacks aren't really arguable

**Comment by AgrTheDev** [comment]
> Also where'd the extension go?

DMCA'd. We aren't storing prodigy's source anymore so we are most likely gonna put it up again

**Comment by afkvido** [comment]
> Membership hacks were cutting into prodigy's revenue. Most of the other hacks aren't really arguable

really dog

**Comment by afkvido** [comment]
Its like boot prototype game state current user source hasMembership true

**Comment by afkvido** [comment]
A line of code killing a megacorp's revenue

get fucked Prodigy

**Pull request closed without merging**
